### ISSUE TITLE
Django template / Cookiecutter template for bootstrapping with logan 

### ISSUE THREAD

**Issue by sumansai14** [dcramer/logan#27]
I really like the way sentry is structured and I was wondering if we could create a Django template or a Cookiecutter template where the project structure could be like sentry and packaging/distribution of the project becomes really easy and the project itself is an app that is standalone. Would love to hear your thoughts.

**Comment by odinho** [comment]
Hi @sumansai14!

I think that sounds like a very good idea. Would you like to take a stab at it?

Sentry itself is no longer using Logan, but doing something similar on their own but with custom code. I've used Logan in one project, and since I was feisty enough to open an issue, I was asked to take some co-mantainership in addition to dcramer. :)

Odin

**Comment by sumansai14** [comment]
Sure. Will take a dig at it when I get some free time over the weekend. I guess it makes sense to start it as a new project. 

Closing the issue.
